language: objective-c
osx_image: xcode8.1
branches:
  only:
    - master

env:
  global:
  - PROJECT_NAME="Codemine.xcodeproj"
  - IOS_FRAMEWORK_SCHEME="Codemine"

  - IOS_SDK=iphonesimulator10.1
  - OSX_SDK=macosx10.12
  - TVOS_SDK=appletvsimulator10.0
  - WATCHOS_SDK=watchsimulator3.1
  matrix:
  - DESTINATION="OS=10.1,name=iPhone 6S Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES"

script:
  - set -o pipefail

  # Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -project "$PROJECT_NAME" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug test | xcpretty;
    else
      xcodebuild -project "$PROJECT_NAME" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  - xcodebuild -project "$PROJECT_NAME" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
after_success:
  - bash <(curl -s https://codecov.io/bash)
